### ISSUE TITLE
fontSize for edges

### ISSUE THREAD

**Issue by notllikethat** [unistbig/shinyCyJS#6]
Hello!

I have been using this package for some project and I needed to be able to change font size for edges' labels. I used the latest version from CRAN (0.0.11) and made a patch which adds fontSize to edges.

Here is the patch:
[edgeFontSize.patch.txt](https://github.com/unistbig/shinyCyJS/files/7546235/edgeFontSize.patch.txt)

**Comment by jhk0530** [comment]
Hi, @notllikethat 

This repository will move to [my personal repository](https://github.com/jhk0530/shinycyjs) since this organization doesn't maintained.

so I'll copy this issue to there and close in here.

Thanks

Kim
